### ISSUE TITLE
Screenshots showing funky terrain generation

### ISSUE THREAD

**Issue by emmagoss** [aswheaton/brave-new-world#4]
Border
![Boreer](https://user-images.githubusercontent.com/47090141/68547285-b489c080-03d7-11ea-9b26-62af24c19abb.png)
Canyon
![Cqnyon](https://user-images.githubusercontent.com/47090141/68547286-b489c080-03d7-11ea-9126-cb851cc42449.png)
Waterfall
![Wqterrqoo](https://user-images.githubusercontent.com/47090141/68547289-b5225700-03d7-11ea-876b-a443c6924c6e.png)

**Comment by aswheaton** [comment]
Issue due to mismatched volatility values at biome borders. Fixed in commit b67994b3ae3c54b737f81975992ef8440a57ebc9.
